In [4]:
import numpy as np

In [50]:
np.random.seed(0)

In [51]:
N = 10

def generateTestValues(n):
    testvalues = [np.random.randint(-500, 500, size=np.random.randint(1,42)) for _ in range(n)]
    return testvalues

testvalues = generateTestValues(N)
testvalues.append([3,5,7,1,4,9])
testvalues.append([1, 9, 3, 5])
testvalues

[array([335]),
 array([-141, -491,  223, -223]),
 array([  99, -430,  -28,  100, -104, -186,  205,  -14,   51, -413, -326,
         100,  349,  177,   37,  345, -428,  277,  416, -385,  476,  255,
         209,  347,  -69,  -52,  350, -401,  484, -323,  255,  297,  159,
        -353,  410,  -77, -212]),
 array([-235,  197]),
 array([  43,  214, -256, -349,  175,   10,  -41,  382, -317, -472,  302,
        -372, -372,  432, -447,  401,   50,  -12,  256, -227, -165, -112,
         117, -458,  -58,   43,  388, -243, -179,  499,  437, -443, -209]),
 array([-381,  279,  -70, -418, -409,  396, -102,  111,   65,  408,  133,
         438, -416, -297, -176,  274,  464, -453,  139, -369,  472,  368,
        -320,  346, -357,  160, -273,  454,  291,  219,  409, -127,  353,
          60, -195,   81, -331,  175,  -52]),
 array([-303,  106, -244,  381,  190, -208,  430,  316,  361, -113,  110,
          54,  473, -132,  499,  417, -299, -117,   12,  406, -130,   55,
         454, -117, -477,  199, -

### Bruteforce Solution

In [52]:
def maxProfit(prices):
    n = len(prices)
    return max([prices[j] - prices[i] for i in range(n) for j in range(n) if i <= j])

In [53]:
bruteforce_solutions = map(maxProfit, testvalues)
bruteforce_solutions

[0, 714, 914, 432, 971, 925, 908, 348, 836, 944, 8, 8]

### LinearTime/Dynamic Programming Solution

`[3,5,7,1,4,9] -> 8`

`[1, 9, 3, 5] -> 8`

In [54]:
def maxProfit(prices):
    if len(prices) == 0:
        return 0, None
    elif len(prices)==1:
        return 0, prices[0]
    else:
        maxDiff, maxSellPrice = maxProfit(prices[1:])

        if maxSellPrice - prices[0] > maxDiff:
            maxDiff = maxSellPrice - prices[0]
        if prices[0] > maxSellPrice:
            maxSellPrice = prices[0]
            
        return maxDiff, maxSellPrice

In [18]:
def maxProfitTail(prices, maxDiff=0, minBuyPrice=None):
    if len(prices) == 0:
        return maxDiff, minBuyPrice
    else:
        if not minBuyPrice:
            minBuyPrice = prices[0]
            
        return maxProfitTail(prices[1:],
                             max([maxDiff, prices[0]-minBuyPrice]),
                             min([minBuyPrice, prices[0]]))

`[3,5,7,1,4,9] -> 8`

In [55]:
dp_solutions = map(maxProfit, testvalues)
dp_solutions

[(0, 335),
 (714, 223),
 (914, 484),
 (432, 197),
 (971, 499),
 (925, 472),
 (908, 499),
 (348, 442),
 (836, 372),
 (944, 463),
 (8, 9),
 (8, 9)]

In [56]:
import operator
dp_solutions = map(operator.itemgetter(0), dp_solutions)
assert dp_solutions == bruteforce_solutions

### Iterative

In [1]:
def maxProfitIterative(prices):
    minBuyPrice = None
    maxDiff = 0
    
    for x in prices:
        if minBuyPrice is None:
            minBuyPrice = x

        maxDiff = max([maxDiff, x - minBuyPrice])
        minBuyPrice = min([minBuyPrice, x])
            
    return maxDiff, minBuyPrice

In [90]:
testvalues.append([2,1,2,1,0,1,2])

In [106]:
itr_solutions = map(maxProfitIterative, testvalues)
itr_solutions 

[(0, 335),
 (714, -491),
 (914, -430),
 (432, -235),
 (971, -472),
 (925, -453),
 (908, -477),
 (348, -352),
 (836, -489),
 (944, -481),
 (8, 1),
 (8, 1),
 (2, 0)]

### Benchmark Bigger *N* values

In [16]:
N = [10**i for i in range(1, 6)]
np.random.seed(0)   

In [17]:
for n in N:
    testvalues = np.random.randint(-500, 500, size=n)
    print "n = 10^{0}".format(n)
    %time maxProfitIterative(testvalues)

n = 10^10
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 329 µs
n = 10^100
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 1.66 ms
n = 10^1000
CPU times: user 16 ms, sys: 0 ns, total: 16 ms
Wall time: 14.2 ms
n = 10^10000
CPU times: user 80 ms, sys: 0 ns, total: 80 ms
Wall time: 99.4 ms
n = 10^100000
CPU times: user 268 ms, sys: 0 ns, total: 268 ms
Wall time: 276 ms


##### Runtime Error encountered when benchmarking recursive variation